/*
 * generated by Xtext 2.10.0
 */
package org.dsl.bimchecker.ui.tests;

import com.google.inject.Injector;
import org.dsl.bimchecker.ui.internal.BimcheckerActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class BimmodelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return BimcheckerActivator.getInstance().getInjector("org.dsl.bimchecker.Bimmodel");
	}

}
