/**
 * generated by Xtext 2.10.0
 */
package org.dsl.bimchecker.validation;

import java.util.HashSet;
import org.dsl.bimchecker.bimmodel.Bimmodel;
import org.dsl.bimchecker.bimmodel.BimmodelPackage;
import org.dsl.bimchecker.bimmodel.Rule;
import org.dsl.bimchecker.validation.AbstractBimmodelValidator;
import org.eclipse.emf.common.util.EList;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class BimmodelValidator extends AbstractBimmodelValidator {
  public final static String DUBPLICATE_NAME = "duplicateName";
  
  @Check
  public void checkRuleNameIsUnique(final Bimmodel m) {
    final HashSet<String> ruleNames = CollectionLiterals.<String>newHashSet();
    EList<Rule> _rules = m.getRules();
    for (final Rule rule : _rules) {
      String _name = rule.getName();
      boolean _add = ruleNames.add(_name);
      boolean _not = (!_add);
      if (_not) {
        this.error("Rule names must be unique.", rule, BimmodelPackage.Literals.RULE__NAME);
      }
    }
  }
}
