/*
 * generated by Xtext 2.10.0
 */
package org.dsl.bimchecker.tests

import com.google.inject.Inject
import org.dsl.bimchecker.bimmodel.Bimmodel
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(BimmodelInjectorProvider)
class BimmodelParsingTest{

	@Inject
	ParseHelper<Bimmodel> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
