/*
 * generated by Xtext 2.10.0
 */
package org.dsl.bimchecker.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BimmodelAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/dsl/bimchecker/parser/antlr/internal/InternalBimmodel.tokens");
	}
}
