/*
 * generated by Xtext 2.10.0
 */
package org.dsl.bimchecker.parser.antlr;

import com.google.inject.Inject;
import org.dsl.bimchecker.parser.antlr.internal.InternalBimmodelParser;
import org.dsl.bimchecker.services.BimmodelGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class BimmodelParser extends AbstractAntlrParser {

	@Inject
	private BimmodelGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBimmodelParser createParser(XtextTokenStream stream) {
		return new InternalBimmodelParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Bimmodel";
	}

	public BimmodelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BimmodelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
