/**
 * generated by Xtext 2.10.0
 */
package org.dsl.bimchecker.ui;

import org.dsl.bimchecker.ui.AbstractBimmodelUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BimmodelUiModule extends AbstractBimmodelUiModule {
  public BimmodelUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
