/*
 * generated by Xtext 2.10.0
 */
package org.dsl.bimchecker.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class BimmodelScopeProvider extends AbstractBimmodelScopeProvider {

}
