/**
 * generated by Xtext 2.10.0
 */
package org.dsl.bimchecker.bimmodel.impl;

import java.util.Collection;

import org.dsl.bimchecker.bimmodel.Aliass;
import org.dsl.bimchecker.bimmodel.BimmodelPackage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Aliass</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.dsl.bimchecker.bimmodel.impl.AliassImpl#getAliass <em>Aliass</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AliassImpl extends MinimalEObjectImpl.Container implements Aliass
{
  /**
   * The cached value of the '{@link #getAliass() <em>Aliass</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAliass()
   * @generated
   * @ordered
   */
  protected EList<String> aliass;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AliassImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BimmodelPackage.Literals.ALIASS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getAliass()
  {
    if (aliass == null)
    {
      aliass = new EDataTypeEList<String>(String.class, this, BimmodelPackage.ALIASS__ALIASS);
    }
    return aliass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BimmodelPackage.ALIASS__ALIASS:
        return getAliass();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BimmodelPackage.ALIASS__ALIASS:
        getAliass().clear();
        getAliass().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BimmodelPackage.ALIASS__ALIASS:
        getAliass().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BimmodelPackage.ALIASS__ALIASS:
        return aliass != null && !aliass.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (aliass: ");
    result.append(aliass);
    result.append(')');
    return result.toString();
  }

} //AliassImpl
