/*
 * generated by Xtext 2.10.0
 */
package org.dsl.bimchecker.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractBimmodelValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.dsl.bimchecker.bimmodel.BimmodelPackage.eINSTANCE);
		return result;
	}
	
}
