/**
 * generated by Xtext 2.10.0
 */
package org.dsl.bimchecker.bimmodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Annotation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.dsl.bimchecker.bimmodel.Annotation#getAnnotationName <em>Annotation Name</em>}</li>
 *   <li>{@link org.dsl.bimchecker.bimmodel.Annotation#getAnnodetail <em>Annodetail</em>}</li>
 * </ul>
 *
 * @see org.dsl.bimchecker.bimmodel.BimmodelPackage#getAnnotation()
 * @model
 * @generated
 */
public interface Annotation extends EObject
{
  /**
   * Returns the value of the '<em><b>Annotation Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Annotation Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annotation Name</em>' attribute.
   * @see #setAnnotationName(String)
   * @see org.dsl.bimchecker.bimmodel.BimmodelPackage#getAnnotation_AnnotationName()
   * @model
   * @generated
   */
  String getAnnotationName();

  /**
   * Sets the value of the '{@link org.dsl.bimchecker.bimmodel.Annotation#getAnnotationName <em>Annotation Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Annotation Name</em>' attribute.
   * @see #getAnnotationName()
   * @generated
   */
  void setAnnotationName(String value);

  /**
   * Returns the value of the '<em><b>Annodetail</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Annodetail</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annodetail</em>' containment reference.
   * @see #setAnnodetail(AnnotationDetail)
   * @see org.dsl.bimchecker.bimmodel.BimmodelPackage#getAnnotation_Annodetail()
   * @model containment="true"
   * @generated
   */
  AnnotationDetail getAnnodetail();

  /**
   * Sets the value of the '{@link org.dsl.bimchecker.bimmodel.Annotation#getAnnodetail <em>Annodetail</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Annodetail</em>' containment reference.
   * @see #getAnnodetail()
   * @generated
   */
  void setAnnodetail(AnnotationDetail value);

} // Annotation
