/**
 * generated by Xtext 2.10.0
 */
package org.dsl.bimchecker.bimmodel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bimmodel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.dsl.bimchecker.bimmodel.Bimmodel#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see org.dsl.bimchecker.bimmodel.BimmodelPackage#getBimmodel()
 * @model
 * @generated
 */
public interface Bimmodel extends EObject
{
  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link org.dsl.bimchecker.bimmodel.Rule}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rules</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see org.dsl.bimchecker.bimmodel.BimmodelPackage#getBimmodel_Rules()
   * @model containment="true"
   * @generated
   */
  EList<Rule> getRules();

} // Bimmodel
