/**
 * generated by Xtext 2.10.0
 */
package org.dsl.bimchecker.bimmodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.dsl.bimchecker.bimmodel.Rule#getName <em>Name</em>}</li>
 *   <li>{@link org.dsl.bimchecker.bimmodel.Rule#getAlialist <em>Alialist</em>}</li>
 *   <li>{@link org.dsl.bimchecker.bimmodel.Rule#getAnnoinfo <em>Annoinfo</em>}</li>
 * </ul>
 *
 * @see org.dsl.bimchecker.bimmodel.BimmodelPackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.dsl.bimchecker.bimmodel.BimmodelPackage#getRule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.dsl.bimchecker.bimmodel.Rule#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Alialist</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alialist</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alialist</em>' containment reference.
   * @see #setAlialist(Aliass)
   * @see org.dsl.bimchecker.bimmodel.BimmodelPackage#getRule_Alialist()
   * @model containment="true"
   * @generated
   */
  Aliass getAlialist();

  /**
   * Sets the value of the '{@link org.dsl.bimchecker.bimmodel.Rule#getAlialist <em>Alialist</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alialist</em>' containment reference.
   * @see #getAlialist()
   * @generated
   */
  void setAlialist(Aliass value);

  /**
   * Returns the value of the '<em><b>Annoinfo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Annoinfo</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annoinfo</em>' containment reference.
   * @see #setAnnoinfo(Annotation)
   * @see org.dsl.bimchecker.bimmodel.BimmodelPackage#getRule_Annoinfo()
   * @model containment="true"
   * @generated
   */
  Annotation getAnnoinfo();

  /**
   * Sets the value of the '{@link org.dsl.bimchecker.bimmodel.Rule#getAnnoinfo <em>Annoinfo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Annoinfo</em>' containment reference.
   * @see #getAnnoinfo()
   * @generated
   */
  void setAnnoinfo(Annotation value);

} // Rule
