/*
 * generated by Xtext 2.10.0
 */
package org.dsl.bimchecker.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractBimmodelScopeProvider extends XbaseBatchScopeProvider {
}
