/*
 * generated by Xtext 2.10.0
 */
package org.dsl.bimchecker.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBimmodelScopeProvider extends DelegatingScopeProvider {
}
