/**
 * generated by Xtext 2.10.0
 */
package org.dsl.bimchecker;

import org.dsl.bimchecker.AbstractBimmodelRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class BimmodelRuntimeModule extends AbstractBimmodelRuntimeModule {
}
