/**
 * generated by Xtext 2.10.0
 */
package org.dsl.bimchecker.ui.contentassist;

import org.dsl.bimchecker.ui.contentassist.AbstractBimmodelProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class BimmodelProposalProvider extends AbstractBimmodelProposalProvider {
}
