/*
 * generated by Xtext 2.10.0
 */
package org.dsl.bimchecker.ui;

import com.google.inject.Injector;
import org.dsl.bimchecker.ui.internal.BimcheckerActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BimmodelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BimcheckerActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BimcheckerActivator.getInstance().getInjector(BimcheckerActivator.ORG_DSL_BIMCHECKER_BIMMODEL);
	}
	
}
